server {
    listen       80;
    server_name  www.holydailyshop.com holydailyshop.com nop.taobao8.top;
    location / {  
            proxy_pass http://127.0.0.1:8080;  #IIS中网站配置的IP和端口,需要要内网的ip
            #设置主机头和客户端真实地址，以便服务器获取客户端真实IP
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP  $remote_addr; 
            proxy_set_header X-Forwarded-Port 80;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Original-Forwarded-For $http_x_forwarded_for;
            client_max_body_size 50m;
        }
    }