
server {
    listen       80;
    server_name  www.holydailyshop.com holydailyshop.com nop.taobao8.top;

    location / {  
         # IIS中网站配置的IP和端口
        proxy_pass http://43.162.120.242:8080; 
        # 传递原始的 Host 头部
        proxy_set_header Host $host;  
       #设置主机头和客户端真实地址，以便服务器获取客户端真实IP
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP  $remote_addr; 
        proxy_set_header X-Forwarded-Port 80;
        client_max_body_size 50m;
    }
}